---
# defaults file for vsphere-tanzu-kubernetes
binary_commands: 
  - 'kubectl'
  - 'kind'
  - 'tkg'

config_file_dir: /root/.tkg

VSPHERE_SERVER: 192.168.0.147
VSPHERE_USERNAME: tkg-user@vsphere.local
VSPHERE_PASSWORD: change_this_password
VSPHERE_DATACENTER: dc-toison-1
VSPHERE_DATASTORE: disk1T
VSPHERE_NETWORK: VM Network
VSPHERE_RESOURCE_POOL: resource-pool-1
VSPHERE_FOLDER: /dc-toison-1/vm/tkg
# VSPHERE_TEMPLATE will be autodetected based on the kubernetes version. Please use VSPHERE_TEMPLATE only to override this behavior
VSPHERE_TEMPLATE: photon-3-kube-v1.19.1-vmware.2
VSPHERE_HAPROXY_TEMPLATE: photon-3-haproxy-v1.2.4-vmware.1
VSPHERE_SSH_AUTHORIZED_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCvQVbEEuvnwGB3rgSkbhaGLHPhjwdCbKJbxc6Pade3JK2ZWKru91MKrHjHOQc7oj47iiJawr4eeBkOJ8Vp+K3Myf1Tx8cwohSLQ9g5IAD3qkFNJ2iz1jEjCDnWkz6eCJ023fPcJNm0mwHMGkIJpLiFxAQtiNw3k0oS54rHl1qkC+wMqNujOX/MG/tGrhtEadk5aXupZGN1QDW0farYTGVHWiLSP7HJ3WFqkdb5nmZWJjSWW4cvstksQClE88UCPRiDOVYHZ1c+709ByVKepEUp+5aB/ksOdDoDApyb5qZiV8ZUFCSiHUWolI8L/JgfO2dXXtZfbsGk8ko01O4pXWb"
SERVICE_CIDR: 100.64.0.0/13
CLUSTER_CIDR: 100.96.0.0/11
VSPHERE_WORKER_DISK_GIB: "50"
VSPHERE_WORKER_NUM_CPUS: "2"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_DISK_GIB: "50"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_HA_PROXY_DISK_GIB: "50"
VSPHERE_HA_PROXY_NUM_CPUS: "2"
VSPHERE_HA_PROXY_MEM_MIB: "4096"

